### PR TITLE
Fix compatibility with credshtash

### PR DESCRIPTION
**Pull request by oleksSol**
Change log:

- bump rust version at rust-toolchain
- fix credstash compatibility (cast: when you put the value into table with original credstash, and try to read with rust one)
- fix help message

### CODE REVIEW

**Comment by psibi** [comment]
@oleksSol Thanks! Can you also update the changelog file: https://github.com/psibi/rucredstash/blob/master/CHANGELOG.md ?

**Comment by captify-osoldatov** [comment]
> @oleksSol Thanks! Can you also update the changelog file: https://github.com/psibi/rucredstash/blob/master/CHANGELOG.md ?

Sure, done.

**Comment by oleksSol** [comment]
Feel free to merge @psibi

**Comment by psibi** [comment]
Thanks!

**Pull request merged**
