### PR TITLE
Few minor changes

### PR DESCRIPTION
**Pull request by mohoff**
Happy to discuss with you these:

- [x] Replace the cloning with `Vec::with_capacity(plaintext.len());`. IMO cleaner and might be more performant too
- [x] remove autoimported import lines
- [x] Getting rid of few `clone()`s
- [x] Few style suggestions

### CODE REVIEW

**Comment by psibi** [comment]
@mohoff Thanks! I ran the integration tests and they seem to be failing:

```
~/g/rucredstash (mohoff-minor-changes) $ aws-env cargo test
   Compiling credstash v0.7.0 (/home/sibi/github/rucredstash)
    Finished test [unoptimized + debuginfo] target(s) in 4.86s
     Running target/debug/deps/credstash-846f6f8719450c9f

running 4 tests
test get_algo256_check ... ok
test pad_integer_check ... ok
test get_algo512_check ... ok
test pad_integer_check_big_num ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/rucredstash-8cd588a0c84cdeab

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-1acdbb71596656a3

running 1 test
test credstash_basic_workflow ... FAILED

failures:

---- credstash_basic_workflow stdout ----
thread 'credstash_basic_workflow' panicked at 'assertion failed: `(left == right)`
  left: `"world12"`,
 right: `""`', tests/integration_test.rs:41:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    credstash_basic_workflow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integration_test'
```

And just to be sure, I switched to the master branch and re-ran the integration tests and they passed fine.

**Comment by mohoff** [comment]
@psibi I got the same integration test failure on `master` and this PR branch, which made me think the changes are alright.

I'm on 

```
rustc --version                                 
rustc 1.45.2 (d3fb005a3 2020-07-31)
```
 and the `cargo test` output is:

```
$ cargo test
running 4 tests
test get_algo256_check ... ok
test get_algo512_check ... ok
test pad_integer_check ... ok
test pad_integer_check_big_num ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/rucredstash-85a4e7e7d6f9757a

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-8779289be3369451

running 1 test
test credstash_basic_workflow ... FAILED

failures:

---- credstash_basic_workflow stdout ----
thread 'credstash_basic_workflow' panicked at 'assertion failed: put_future.is_ok()', tests/integration_test.rs:31:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    credstash_basic_workflow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integration_test'
```

**Comment by psibi** [comment]
@mohoff That error indicates that you had some entries in the DynamoDB table before you ran the test. (I'm assuming you ran the integration tests from your branch and then switched to `master` branch and ran it again).

So, can you clean all the entries from the dynamoDB table before running the test. (You can use a combination of `rucredstash getall` and `rucredstash delete`) to achieve it.

**Comment by mohoff** [comment]
@psibi I don't have any AWS/DynamoDB setup, which is probably why I see the identical error output between `master` and this PR.

Looks like there's no way to narrow the issue down without being setup on AWS. Since there are very few changes in this PR, do you want to experiment a bit yourself to find the real issue?

**Comment by psibi** [comment]
Sure, I could do that. Thanks!

**Pull request merged**
